# Generated by Django 3.2.15 on 2022-10-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minutes',
            new_name='time_minute',
        ),
    ]
